 services:
    pockethost:
      image: node:20-alpine
      container_name: pockethost
      restart: unless-stopped
      privileged: true
      working_dir: /app
      command: |
        sh -c '
          apk add --no-cache git bash docker-cli openssl curl python3 make g++ ca-certificates && \
          npm install -g pnpm@9 tsx && \
          git clone https://github.com/pockethost/pockethost.git /app || (cd /app && git pull) && \
          cd /app && pnpm install --frozen-lockfile && \
          mkdir -p /data /home/pockethost/.pockethost/ssl && \
          openssl req -x509 -newkey rsa:4096 -keyout /home/pockethost/.pockethost/ssl/tls.key -out /home/pockethost/.pockethost/ssl/tls.cert -days 365 -nodes -subj "/CN=*.store.jwls.co" && \
          cd /app/packages/pockethost && NODE_ENV=production tsx ./src/cli/index.ts serve
        '
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - pockethost_app:/app
        - pockethost_data:/data
        - pockethost_home:/home/pockethost/.pockethost
      ports:
        - "18090:8090"
        - "13000:3000"
      environment:
        APEX_DOMAIN: store.jwls.co
        HTTP_PROTOCOL: "https:"
        MOTHERSHIP_NAME: pockethost-central
        MOTHERSHIP_ADMIN_USERNAME: admin@jwls.co
        MOTHERSHIP_ADMIN_PASSWORD: ChangeThisPassword123!
        MOTHERSHIP_PORT: 8090
        NODE_ENV: production
        PH_HOME: /home/pockethost/.pockethost
        DATA_ROOT: /data
        DAEMON_PORT: 3000
        SSL_KEY: /home/pockethost/.pockethost/ssl/tls.key
        SSL_CERT: /home/pockethost/.pockethost/ssl/tls.cert
        DOCKER_CONTAINER_HOST: host.docker.internal

  volumes:
    pockethost_app:
      driver: local
    pockethost_data:
      driver: local
    pockethost_home:
      driver: local
