  services:
    pockethost:
      image: node:20-alpine
      container_name: pockethost
      restart: unless-stopped
      privileged: true
      working_dir: /app

      command: |
        sh -c '
          echo "Installing system dependencies..."
          apk add --no-cache git bash docker-cli openssl curl python3 make g++ ca-certificates

          echo "Installing Node.js global packages..."
          npm install -g pnpm@9 tsx

          echo "Cloning or updating PocketHost repository..."
          if [ ! -d "/app/.git" ]; then
            git clone https://github.com/pockethost/pockethost.git /app
          else
            cd /app && git pull origin main
          fi

          echo "Installing Node dependencies..."
          cd /app
          pnpm install --frozen-lockfile

          echo "Creating required directories..."
          mkdir -p /data /home/pockethost/.pockethost

          echo "Starting PocketHost without SSL (Dokploy handles it)..."
          cd /app/packages/pockethost
          NODE_ENV=production tsx ./src/cli/index.ts edge daemon serve
        '

      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - pockethost_app:/app
        - pockethost_data:/data
        - pockethost_home:/home/pockethost/.pockethost

      ports:
        - "8090:8090"
        - "3000:3000"
        - "3001:80"
        - "3443:443"
        - "21:21"
        - "10000-20000:10000-20000"

      environment:
        APEX_DOMAIN: store.jwls.co
        HTTP_PROTOCOL: "http:"
        MOTHERSHIP_NAME: pockethost-central
        MOTHERSHIP_ADMIN_USERNAME: admin@jwls.co
        MOTHERSHIP_ADMIN_PASSWORD: ChangeThisPassword123!
        MOTHERSHIP_PORT: 8090
        MOTHERSHIP_SEMVER: "0.22.*"
        NODE_ENV: production
        PH_HOME: /home/pockethost/.pockethost
        DATA_ROOT: /data
        DAEMON_PORT: 3000
        DAEMON_PB_IDLE_TTL: 300000
        DOCKER_CONTAINER_HOST: host.docker.internal
        DEBUG: "false"

  volumes:
    pockethost_app:
      driver: local
    pockethost_data:
      driver: local
    pockethost_home:
      driver: local
